quarkus.http.port=8090

#silent or gst
reson8dev.audiopath=gst

%test.reson8dev.audiopath=silent

%dev.reson8.k8s.thanos.base-url=https://thanos-querier-openshift-monitoring.apps.c3.fka.coherentnetworksolutions.com/
%dev.reson8.k8s.thanos.ignore-certs=true

%test.reson8.k8s.thanos.base-url=https://thanos-querier-openshift-monitoring.apps.c3.fka.coherentnetworksolutions.com/
%test.reson8.k8s.thanos.ignore-certs=true

%dev.quarkus.log.category."com.coherentnetworksolutions".level=TRACE
%test.quarkus.log.category."com.coherentnetworksolutions".level=DEBUG


quarkus.log.min-level=TRACE
quarkus.log.console.level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.http.access-log.enabled=false

# reson8.source.mode=canned
# %test.reson8.source.mode=canned