quarkus.http.port=8090

#silent or gst
reson8dev.audiopath=gst

%test.reson8dev.audiopath=silent


%dev.quarkus.log.category."com.coherentnetworksolutions".level=DEBUG
%test.quarkus.log.category."com.coherentnetworksolutions".level=DEBUG


quarkus.log.min-level=DEBUG
quarkus.log.console.level=DEBUG
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n

# reson8.source.mode=canned
# %test.reson8.source.mode=canned