FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.24
USER root
RUN dnf install -y \
      gstreamer1 \
      gstreamer1-plugins-base \
      gstreamer1-plugins-good \
    && dnf clean all
USER 185
