%dev.quarkus.http.port=8081
%dev.quarkus.http.logging.enabled=true

quarkus.http.port=8080
# Required when both container-image-openshift and container-image-podman are present (default = in-cluster build).
quarkus.container-image.builder=openshift
quarkus.openshift.route.expose=true
quarkus.openshift.env.vars.quarkus-kubernetes-client-trust-certs=true
quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000
quarkus.container-image.group=stress-test

quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.binder.http-server.enabled=true

quarkus.openshift.prometheus.annotations=true
quarkus.openshift.prometheus.generate-service-monitor=true


quarkus.micrometer.binder.http-server.match-patterns=*
