conditional-dev-dependencies=io.quarkus\:quarkus-oidc-dev\:\:jar\:3.34.5
deployment-artifact=io.quarkus\:quarkus-oidc-deployment\:3.34.5
provides-capabilities=io.quarkus.oidc
requires-quarkus-version=[3.34,)
