{{- if .Values.oauthClientSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.oauthClientSecret.name }}
  labels:
    {{- include "reson8.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "reson8.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
