apiVersion: v1
kind: Service
metadata:
  name: {{ include "reson8.fullname" . }}
  labels:
    {{- include "reson8.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "reson8.selectorLabels" . | nindent 4 }}
