{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reson8.serviceAccountName" . }}
  labels:
    {{- include "reson8.labels" . | nindent 4 }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ default (include "reson8.fullname" .) .Values.serviceAccount.oauthRedirectRouteName }}"}}
{{- end }}
